# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 870bac21c67522de93da0736cf74c977d930b17ce7b81e073740cfa1cdcf5c9cabc937c6266a98f414dabe13ab59f45d1125dc41ce301405aef565c3cc3bf34a

test:
  secret_key_base: 6f2337db5631b5f60f8899401b4edc5be1e75b719442e18f89f7c4a2829edd16ea03e56147b4397af566c398e70bf3ea32ade139ff4875d8cb2a8e2fb19f0cf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
